name: Scala CI + Coverage

on:
  push:
    branches: [ main, MVC, CI-Travis ]
  pull_request:
    branches: [ main, MVC, CI-Travis ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install sbt
        run: |
          curl -L -o sbt.deb https://piccolo.link/sbt-1.9.7.deb
          sudo dpkg -i sbt.deb

      - name: compile
        run: sbt compile

      - name: run tests
        run: sbt test

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install sbt
        run: |
          curl -L -o sbt.deb https://piccolo.link/sbt-1.9.7.deb
          sudo dpkg -i sbt.deb

      - name: Build Project and export Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          sbt clean coverage test coverageReport
          sbt coveralls
